# Generated by Django 5.0.7 on 2024-07-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=30)),
                ("password", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=70)),
                ("surname", models.CharField(max_length=70)),
            ],
        ),
    ]
