# Generated by Django 5.0.7 on 2024-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagecolorizer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("processed", models.BooleanField(default=False)),
                ("result", models.TextField(blank=True, null=True)),
                ("queue_position", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
