# Generated by Django 5.0.7 on 2024-07-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagecolorizer", "0002_uploadedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="processing_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
