# Generated by Django 5.0.7 on 2024-07-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "imagecolorizer",
            "0003_uploadedimage_height_uploadedimage_processing_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
