# Generated by Django 5.0.7 on 2024-07-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "imagecolorizer",
            "0008_rename_credits_usercredits_remaining_credits_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="image_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
