# Generated by Django 5.0.7 on 2024-07-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagecolorizer", "0009_uploadedimage_image_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="processed_images/")),
                ("result", models.TextField(blank=True, null=True)),
                ("image_hash", models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
