# Generated by Django 5.0.7 on 2024-08-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagecolorizer", "0010_processedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
                ("credits", models.PositiveIntegerField()),
                ("limit", models.PositiveIntegerField()),
                ("used_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
