# Generated by Django 5.0.7 on 2024-08-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagecolorizer", "0013_couponusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="image_score",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
