# Generated by Django 5.0.7 on 2024-08-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagecolorizer", "0014_gallery_image_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="image_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
