# Generated by Django 5.0.7 on 2024-08-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagecolorizer", "0016_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="g_check",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
